name: cubes
title: Cubes
version: "1.0"
summary: A simple game of Cubes.
description: |
  Cubes 50 kb :P
  --------------

  Content:
  ========
  1. How to play
  2. Requirements
  3. Parameters
  4. Cheats
  5. Greets


  1. How to play
  ==============
  Try not to collide with the red cubes and collect the power-ups (blue thingies). By tapping left/right you can change your current position. Use space to jump. It's that easy :P 

  There are the following power-ups avaiable:
   1. Speed up
   2. Speed Down
   3. Jump Enabled
   4. Drunken Mode
   5. Invincible
   6. "Flashbang"
   7. No Cubes
   8. get a life 
   9. Megajump
   10.Powerup-Mania
   11.Random chaos


  2. Requirements
  ===============
  fast pc, fast gfx-card, sound :p


  3. Parameters
  =============
  Here are some nice parameters you can use for your enjoyment:
   "-gentex" : generates textures & saves them to disk. next time you start the game, those saved textures are used -> faster startup :D
   "-qt"     : play windowed and in 400x300. whoa, what a feature!!1
  use only one parameter at a time.


  4. Cheats
  =========
  Yes. there are some. they suck :P


  5. Greets
  =========
  read the nfo :P too lazy to copy the names :D 
  special thanks must go to delphigl.com and the beta-testers of the game :)

grade: stable
icon: snap/gui/cubes.png

base: core18
confinement: strict

architectures:
  - build-on: amd64
  - build-on: i386

environment:
  WINEDLLOVERRIDES: "$WINEDLLOVERRIDES;mscoree,mshtml="    # Prevent pop-ups about Wine Mono and Wine Gecko

apps:
  cubes:
    extensions: [ gnome-3-28 ]
    command: bin/sommelier run-exe
    environment:
      RUN_EXE: "$SNAP/meta/gui/Cubes.exe"
  wine:
    extensions: [ gnome-3-28 ]
    command: bin/sommelier run-exe
  winetricks:
    extensions: [ gnome-3-28 ]
    command: bin/sommelier run-exe

parts:
  sommelier:
    plugin: make
    source: https://github.com/snapcrafters/sommelier-core.git

plugs:
  wine-runtime:
    interface: content
    target: $SNAP/wine-runtime
    default-provider: wine-platform-runtime
  wine-5-stable:
    interface: content
    target: $SNAP/wine-platform
    default-provider: wine-platform-5-stable
